# Generated by Django 2.1.7 on 2019-03-01 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('patronimyc', models.CharField(max_length=60)),
                ('position', models.CharField(max_length=60)),
                ('employee_date', models.DateField()),
                ('salary', models.IntegerField(default=0, null=True)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.Boss')),
            ],
        ),
    ]
