# Generated by Django 2.1.7 on 2019-03-09 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20190303_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employeedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('patronimyc', models.CharField(max_length=60)),
                ('position', models.CharField(max_length=60)),
                ('employee_date', models.DateField()),
                ('salary', models.PositiveIntegerField(default=0, null=True)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boss', to='mainpage.Boss')),
            ],
        ),
        migrations.RemoveField(
            model_name='employee_data',
            name='boss',
        ),
        migrations.DeleteModel(
            name='Employee_data',
        ),
    ]
