# Generated by Django 2.1.7 on 2019-03-09 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20190309_1402'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employeedata',
            new_name='Employee_data',
        ),
    ]
