# Generated by Django 2.1.7 on 2019-03-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_auto_20190309_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_data',
            name='employee_image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
